sonar.projectKey=taskmanager-backend
sonar.projectName=TaskManager Backend
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,coverage/**,*.json
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
